import{PUBLICATION_TYPES}from"../js/config.js";import{createPublication,deleteImage,deletePublication,getAdminPublications,getPublicationById,updatePublication,uploadImage}from"../js/promotion-service.js";import{validateImage}from"../js/validation.js";import{getThemeColor,resetThemeColor,saveThemeColor}from"../js/theme.js";import{formatFileSize,optimizeImage}from"../js/image-optimizer.js";import{getTitleSelection,OTHER_TITLE_VALUE,resolvePublicationTitle}from"../js/title-presets.js";
const $=s=>document.querySelector(s),form=$("#publication-form"),list=$("#publication-list"),listStatus=$("#list-status"),message=$("#form-message"),previewWrap=$("#image-preview"),preview=$("#preview-image"),saveButton=$("#save-button");let imageKey="",imageUrl="",selectedFile=null,page=1,totalPages=1,busy=false;
const today=()=>new Intl.DateTimeFormat("en-CA",{timeZone:"America/Costa_Rica"}).format(new Date());
function notice(text,kind="success"){message.textContent=text;message.className=`message message--${kind}`;message.hidden=false;}
function state(item){const date=today();if(item.endDate<date)return"expired";if(!item.active)return"inactive";if(item.startDate>date)return"scheduled";return"active";}const labels={active:"Activa",inactive:"Inactiva",expired:"Vencida",scheduled:"Programada"};
function setPreview(url,key=""){imageUrl=url||"";imageKey=key||"";previewWrap.hidden=!imageUrl;preview.src=imageUrl;}
function syncTitleField(){const custom=$("#title-preset").value===OTHER_TITLE_VALUE,input=$("#title");$("#custom-title-field").hidden=!custom;if(!custom)input.value=$("#title-preset").value;else{input.value="";input.focus();}}
function setTitleSelection(title){const selection=getTitleSelection(title);$("#title-preset").value=selection.preset;$("#title").value=selection.custom||selection.preset;$("#custom-title-field").hidden=selection.preset!==OTHER_TITLE_VALUE;}
function reset(){form.reset();$("#publication-id").value="";$("#active").checked=true;selectedFile=null;setPreview("");syncTitleField();$("#form-title").textContent="Nueva publicación";saveButton.textContent="Guardar publicación";$("#cancel-edit").hidden=true;$("#description-count").textContent="0";}
$("#title-preset").addEventListener("change",syncTitleField);syncTitleField();
const data=()=>({type:$("#type").value,title:resolvePublicationTitle($("#title-preset").value,$("#title").value),description:$("#description").value,imageKey,startDate:$("#start-date").value,endDate:$("#end-date").value,active:$("#active").checked,buttonText:$("#button-text").value,buttonUrl:$("#button-url").value});
function button(text,className,action){const b=document.createElement("button");b.type="button";b.className=`button ${className}`;b.textContent=text;b.addEventListener("click",action);return b;}
function itemNode(item){const article=document.createElement("article");article.className="publication";const image=item.imageUrl?document.createElement("img"):document.createElement("div");if(item.imageUrl){image.src=item.imageUrl;image.alt=`Imagen de ${item.title}`;image.className="publication__image";}else{image.className="publication__placeholder";image.textContent="Sin imagen";}const content=document.createElement("div"),top=document.createElement("div"),title=document.createElement("h3"),badge=document.createElement("span"),meta=document.createElement("p"),actions=document.createElement("div");top.className="publication__top";title.textContent=item.title;const s=state(item);badge.className=`badge badge--${s}`;badge.textContent=labels[s];top.append(title,badge);meta.textContent=`${PUBLICATION_TYPES[item.type]} · ${item.startDate} a ${item.endDate}`;actions.className="publication__actions";actions.append(button("Editar","button--secondary",()=>edit(item.id)),button(item.active?"Desactivar":"Activar","button--quiet",()=>toggle(item)),button("Eliminar","button--danger-quiet",()=>remove(item)));content.append(top,meta,actions);article.append(image,content);return article;}
async function render(){listStatus.hidden=false;listStatus.textContent="Cargando publicaciones…";list.replaceChildren();try{const result=await getAdminPublications({page,pageSize:6,status:$("#status-filter").value});totalPages=result.pagination.totalPages||1;if(page>totalPages){page=totalPages;return render();}if(!result.data.length){listStatus.textContent="No hay publicaciones para este filtro.";}else{listStatus.hidden=true;list.append(...result.data.map(itemNode));}$("#admin-pagination").hidden=result.pagination.totalPages<=1;$("#admin-page-status").textContent=`Página ${page} de ${totalPages}`;$("#admin-previous").disabled=page<=1;$("#admin-next").disabled=page>=totalPages;}catch(error){listStatus.textContent=error.message;}}
async function edit(id){const item=await getPublicationById(id);$("#publication-id").value=id;for(const [selector,value]of[["#type",item.type],["#description",item.description],["#start-date",item.startDate],["#end-date",item.endDate],["#button-text",item.buttonText],["#button-url",item.buttonUrl]])$(selector).value=value||"";setTitleSelection(item.title);$("#active").checked=item.active;setPreview(item.imageUrl,item.imageKey);$("#form-title").textContent="Editar publicación";saveButton.textContent="Actualizar publicación";$("#cancel-edit").hidden=false;form.scrollIntoView({behavior:"smooth"});}
async function toggle(item){await updatePublication(item.id,{...item,active:!item.active});notice(`Publicación ${item.active?"desactivada":"activada"}.`);await render();}
async function remove(item){if(!confirm(`¿Eliminar “${item.title}”?`))return;await deletePublication(item.id);notice("Publicación eliminada correctamente.");await render();}
form.addEventListener("submit",async event=>{event.preventDefault();if(busy)return;busy=true;saveButton.disabled=true;saveButton.textContent="Guardando…";let uploaded=null;try{if(selectedFile){uploaded=await uploadImage(selectedFile);imageKey=uploaded.key;}const id=$("#publication-id").value;if(id)await updatePublication(id,data());else await createPublication(data());notice(id?"Publicación actualizada correctamente.":"Publicación guardada correctamente.");reset();await render();}catch(error){if(uploaded)try{await deleteImage(uploaded.key);}catch{}notice(error.message||"No se pudo guardar.","error");}finally{busy=false;saveButton.disabled=false;if($("#publication-id").value)saveButton.textContent="Actualizar publicación";}});
$("#image").addEventListener("change",async event=>{const file=event.target.files[0],errors=validateImage(file);if(errors.length){event.target.value="";notice(errors.join("\n"),"error");return;}if(!file){selectedFile=null;return;}try{notice("Optimizando imagen…");selectedFile=await optimizeImage(file);setPreview(URL.createObjectURL(selectedFile),imageKey);notice(selectedFile===file?`Imagen lista (${formatFileSize(file.size)}).`:`Imagen optimizada: ${formatFileSize(file.size)} → ${formatFileSize(selectedFile.size)}.`);}catch{selectedFile=file;setPreview(URL.createObjectURL(file),imageKey);notice("No fue posible comprimir la imagen; se conservará el archivo original.","error");}});$("#remove-image").addEventListener("click",()=>{selectedFile=null;setPreview("");$("#image").value="";});$("#description").addEventListener("input",event=>$("#description-count").textContent=event.target.value.length);$("#cancel-edit").addEventListener("click",reset);$("#status-filter").addEventListener("change",()=>{page=1;render();});$("#admin-previous").addEventListener("click",()=>{if(page>1){page--;render();}});$("#admin-next").addEventListener("click",()=>{if(page<totalPages){page++;render();}});
const themeInput=$("#theme-color"),themeMessage=$("#theme-message");themeInput.value=getThemeColor();$("#apply-theme").addEventListener("click",()=>{saveThemeColor(themeInput.value);themeMessage.textContent="Color aplicado correctamente.";themeMessage.hidden=false;});$("#reset-theme").addEventListener("click",()=>{themeInput.value=resetThemeColor();themeMessage.textContent="Se restableció el color original.";themeMessage.hidden=false;});render();
